<?php

	/*
	
	PLEASE DO NOT EDIT THIS FILE DIRECTLY

	Please modify via Admin > Tools > Settings > Weight Loss Tracker

	 */
	
	// -----------------------------------------------------------------------------------
	// Define whether Imperial and Units
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-units') || 'kg' == get_option('ws-ls-units'))
	{
		define('WE_LS_DATA_UNITS', 'kg');
		define('WE_LS_IMPERIAL_WEIGHTS', false);	
	}
	else
	{
		define('WE_LS_DATA_UNITS', get_option('ws-ls-units'));
		define('WE_LS_IMPERIAL_WEIGHTS', true);
	}

	// -----------------------------------------------------------------------------------
	// Define if target weights enabled
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-allow-targets') || 'no' == get_option('ws-ls-allow-targets'))
		define('WE_LS_ALLOW_TARGET_WEIGHTS', false);
	else
		define('WE_LS_ALLOW_TARGET_WEIGHTS', true);


	// -----------------------------------------------------------------------------------
	// Plot points on graph?
	// -----------------------------------------------------------------------------------
	if ('no' == get_option('ws-ls-allow-points'))
		define('WE_LS_ALLOW_POINTS', false);
	else
		define('WE_LS_ALLOW_POINTS', true);

	// -----------------------------------------------------------------------------------
	// Define whether to use tabs
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-use-tabs') || 'no' == get_option('ws-ls-use-tabs'))
		define('WE_LS_USE_TABS', false);
	else
		define('WE_LS_USE_TABS', true);
	
	// -----------------------------------------------------------------------------------
	// Define whether to support Avada theme
	// -----------------------------------------------------------------------------------
	if (false == get_option('ws-ls-support-avada') || 'no' == get_option('ws-ls-support-avada'))
		define('WE_LS_SUPPORT_AVADA_THEME', false);
	else
		define('WE_LS_SUPPORT_AVADA_THEME', true);

	// -----------------------------------------------------------------------------------------
	// AC: Other defined fields that can't be changed in settings page.
	// -----------------------------------------------------------------------------------------
	
	define('WE_LS_TITLE', "Weight Loss Tracker");
	define('WE_LS_SLUG', "weight-loss-tracker");
	define('WE_LS_TABLENAME', "WS_LS_DATA"); 
	define('WE_LS_TARGETS_TABLENAME', "WS_LS_DATA_TARGETS"); 
	define('WE_LS_VERSION', "WS_LS_VERSION"); 
